### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vladipus**
The docs and the sample are now completely according to #66

### CODE REVIEW

**Comment by P-p-H-d** [comment]
I think the correct way is more like this:
```

typedef struct mystruct_s {
  ISHARED_PTR_INTERFACE(ishared_mystruct, struct mystruct_s);
  char *message;
} mystruct_t;

static inline void mystruct_init(mystruct_t *p) { p->message = NULL; }
static inline void mystruct_clear(mystruct_t *p) { free(p->message); }

ISHARED_PTR_DEF(ishared_mystruct, mystruct_t, (INIT(mystruct_init M_IPTR), CLEAR(mystruct_clear M_IPTR)))

void f(void) {
  mystruct_t *p = ishared_mystruct_init_new();
  p->message = strdup ("Hello");
  buffer_mystruct_push(g_buff1, p);
  buffer_mystruct_push(g_buff2, p);
  ishared_mystruct_clear(p);
}
```

There is a difference between NEW / DEL being defined, ommited and disabled:

- ( NEW(f) ): the function f is the method of the operator NEW
- ( ): the operator NEW is omitted, and the default global operation for NEW is used.
- ( NEW(0) ): the operator NEW is disabled, and it can never be used.

To have the _init_new function, you need to have an explicit method for the INIT operator, 
and a not disabled NEW operator.

I am not sure if I explain this in the documentation...

**Comment by vladipus** [comment]
I'm a bit confused. I had both INIT and CLEAR functions defined, but the `init_new` was still unavailable. Did I get you wrong?

**Comment by P-p-H-d** [comment]
I copy paste the code above, and I get the generated code:

`static inline ishared_mystruct_t ishared_mystruct_init_new(void) { mystruct_t *ptr = malloc (sizeof (mystruct_t)); if (ptr == ((void *)0)) { do { fprintf(stderr, "ERROR(M*LIB): Cannot allocate %zu bytes of memory at (%s:%s:%d).\n", (size_t) (sizeof(mystruct_t)), "t.c", __func__, 11); abort(); } while (0); return ((void *)0); } mystruct_init ( & *ptr ); do { *(&ptr->ishared_mystruct_cpt) = (1); } while (0); return ptr; }
`

What is your ouput (option -E)?

**Comment by vladipus** [comment]
Yes, this now works. I've made some *heavy* refactors of the docs already in my fork, according to modern Markdown guidelines. It also features some nice-looking C-colored snippets. Go check it out! =)

**Pull request closed without merging**
