### PR TITLE
Docs upgrade & renaming functionality

### PR DESCRIPTION
**Pull request by vladipus**
I've made some heavy refactors of the docs, according to the modern Markdown guidelines (https://github.com/DavidAnson/markdownlint/blob/v0.20.4/doc/Rules.md)
It also now features some nice-looking C-colored snippets.

The renaming functionality was implemented for some core functions and the weird `_p` suffixed methods. The documentation for the new feature is also written accordingly and with a sample code.

### CODE REVIEW

**Comment by vladipus** [comment]
Marked as WIP, while I get more functions covered.

**Comment by vladipus** [comment]
Phew! I'm almost done on that one. I'm also auditing the code, correcting formatting, typos, misspellings and learning a lot! The library is just fantastic! I'll make sure everything works as expected, run all the tests and double-checking the final result.

**Comment by vladipus** [comment]
Completed. Now resolving the conflicts.

**Comment by vladipus** [comment]
Everything is resolved, tested and should be ready for merge, you willing.

**Comment by P-p-H-d** [comment]
Pull request closed as it cannot be merged in its current state.

**Pull request closed without merging**
